### ISSUE TITLE
大佬可以提供转换到onnx的脚本吗？

### ISSUE THREAD

**Issue by passion765** [lonePatient/NeZha_Chinese_PyTorch#1]

**Comment by lonePatient** [comment]
@passion765 网上或者github有很多的，我自己之前转没啥问题的，转onnx没啥难度的啊，你是转化遇到问题？

**Comment by passion765** [comment]
> @passion765 网上或者github有很多的，我自己之前转没啥问题的，转onnx没啥难度的啊，你是转化遇到问题？

非常感谢大佬回复 ， 我转模型的遇到raise RuntimeError('Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice 这样的错误，不知道这个是我的数据输入有问题吗？代码如下：

 input_ids = torch.ones(1, 255,dtype=torch.int64, device="cuda")
    #input_ids_f = torch.randn(1,255,device="cuda")
    attention_mask = torch.ones(1,255,dtype=torch.int64, device="cuda")
    token_type_ids = torch.zeros(1,255,dtype=torch.int64, device="cuda")

torch.onnx.export(model,
                      my_input,
                      export_onnx_file,
                      verbose=True,
                      # opset_version=10,
                      #do_constant_folding=True,  
                      #operator_export_type=OPERATOR_EXPORT_TYPE,
                      input_names=input_names,  
                      output_names=out_names,  
                      )
