### ISSUE TITLE
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED 

### ISSUE THREAD

**Issue by JeremySun1224** [lonePatient/NeZha_Chinese_PyTorch#4]
您好，我在调用nezha-large-www模型的时候出现以下的错：
```RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED ```
环境是：```linux，transformers==4.4.1，pytorch==1.4```
请问您知道怎么修复吗

**Comment by lonePatient** [comment]
@JeremySun1224  你是加载md提供的pytorch模型文件吗？如果是的话，应该是你的pytorch版本过低了，你可以基于1.4的自己转下模型，或者需要升级pytorch。

**Comment by JeremySun1224** [comment]
@lonePatient 嗯嗯 很感谢您的指点，是您说的这个问题，已经解决了，感谢！
