### ISSUE TITLE
想问一下，可以直接使用transformer里的bert模型，直接来加载nezha权重可以吗

### ISSUE THREAD

**Issue by xuanzebi** [lonePatient/NeZha_Chinese_PyTorch#9]
顺便想问一下，和huawei官方的nezha这个有什么区别呢

**Comment by zhengyanzhao1997** [comment]
应该是不行的，transformer的bert模型 是没有基于sin/cos的相对位置编码的设定

**Comment by xuanzebi** [comment]
> 应该是不行的，transformer的bert模型 是没有基于sin/cos的相对位置编码的设定

是的， 我试了试，效果不好。

**Comment by zhengyanzhao1997** [comment]
https://blog.csdn.net/weixin_45839693/article/details/112910652?spm=1001.2014.3001.5501 我用TF做过简单的魔改，你在pytorch上可以试试
